services:
  api:
    image: ghcr.io/slowlydev/f1-dash-api:latest
    restart: unless-stopped
    environment:
      - RUST_LOG=api=info
      - ADDRESS=0.0.0.0:80
      - ORIGIN=${FRONTEND_URL}

  realtime:
    image: ghcr.io/slowlydev/f1-dash-realtime:latest
    restart: unless-stopped
    ports:
      - "4000:80"
    environment:
      - RUST_LOG=realtime=info
      - ADDRESS=0.0.0.0:80
      - ORIGIN=${FRONTEND_URL}

  web:
    build:
      context: ./dashboard
      dockerfile: dockerfile
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on:
      - realtime
      - api
    environment:
      - NEXT_PUBLIC_LIVE_URL=${REALTIME_URL}
      - API_URL=http://api:80
